#!/usr/bin/python

import socket
import datetime
import os
import sys
import subprocess
import sender

graylog_server = sender.graylog_server()
port = int(sender.graylog_input_port())

# Application log
LogDir = "/var/log/pysender/"
LogFile = "/var/log/pysender/check_connection.log"
today_date = datetime.datetime.strftime(datetime.datetime.now(), '%Y-%m-%d %H:%M:%S')
if os.path.isdir(LogDir) == False:
    subprocess.call('mkdir /var/log/pysender', shell=True)

try:
    check_it = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    check_it.connect((graylog_server, port))
    check_it.send('connected to GrayLog')
    packet = check_it.recv(1024)
    check_it.close()
    log_file = open(LogFile, 'a+')
    log_file.write(hoy + ' GrayLog connection lost - %s\n' % str(e))
    log_file.close()
except Exception, e:
    hoy = datetime.datetime.strftime(datetime.datetime.now(), '%Y-%m-%d %H:%M:%S')
    log_file = open(LogFile, 'a+')
    log_file.write(hoy + ' - socket - Unable to establish connection with GrayLog - ' + str(e) + '\n')
    log_file.close()
    sys.exit(1)
