#!/usr/bin/python

import socket, datetime, os

graylog_server = '192.168.1.100'
port = 12202

# Application log
LogDir = "/var/log/PySender/"
LogFile = "/var/log/PySender/check_connection.log"  
hoy = datetime.datetime.strftime(datetime.datetime.now(), '%Y-%m-%d %H:%M:%S')
if os.path.isdir(LogDir) == False:
        subprocess.call('mkdir /var/log/PySender', shell=True)

try:
	check_it = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	check_it.connect((graylog_server, port))
	check_it.send('connected to GrayLog')
	packet = check_it.recv(1024)
	check_it.close()
	log_file = open(LogFile, 'a')
	log_file.write(hoy + ' GrayLog connection lost!!!')
	log_file.close()
except Exception,e:
	log_file = open(LogFile, 'a')
	log_file.write(hoy + ' - socket - Unable to establish connection with GrayLog - ' + str(e) + '\n')
	log_file.close() 